### ISSUE TITLE
Cleanup TODO and FIXME comments in code

### ISSUE THREAD

**Issue by iondbproject** [iondbproject/iondb#10]
There are lots of TODOs and FIXMEs scattered in our code base. Lots of them haven't been resolved because they require discussion. Some of them are old and have already been resolved.

In general, if you encounter a TODO that you can fix reasonably quickly, do so. 

If it is not in an area you're familiar with, post an issue with the TODO, reference the line(s) of code, and **remove** the TODO from within the code. Do the same for TODOs that require further discussion from the group.

If you encounter a TODO that has already been finished, remove it from the code.

**Comment by Stickerpants** [comment]
Issue moved to internal task tracker.
