### ISSUE TITLE
b+tree duplicate keys

### ISSUE THREAD

**Issue by leifzars** [iondbproject/iondb#112]
I really appreciate this code, nice work.

Is your support for duplicate keys fully supported?
Can you describe the method you used to support this feature?

Thanks

**Comment by leifzars** [comment]
After some looking, it seems to be partially implemented.

**Comment by danaack** [comment]
Hi @leifzars, thank you for your interest in IonDB! Currently duplicate keys are supported for the B+ Tree and Skip List dictionary implementations.

**Comment by leifzars** [comment]
I submitted two pull requests for bugs found in the duplicate key feature. 
So now things are working well
