### ISSUE TITLE
Implement ion_status_t behavior

### ISSUE THREAD

**Issue by iondbproject** [iondbproject/iondb#13]
`ion_status_t` is currently partially implemented. To fully implement `ion_status_t`, the following must be done:

* The return types of all affected methods need to be adjusted across the dictionary, handler, and implementation levels.
* Any unit test affected will also need to be changed to accommodate. Reading an `err` will now read the `err` member of the `ion_status_t` struct. These unit tests *should* also assert the rows affected is reported correctly.
* All implementations must properly support and return the struct, with rows affected.

**Comment by Stickerpants** [comment]
This task has been done and is merged into development. See 99be250271afac701148f573d7573a577855b27e
