### ISSUE TITLE
Ion_file to be removed

### ISSUE THREAD

**Issue by iondbproject** [iondbproject/iondb#14]
The generalized file interface, `ion_file`, is currently only used by the B+ tree. With the introduction of the SD File IO Intercept, `ion_file` is redundant and no longer needed.

`ion_file` should be removed, and any previous references (most likely only in the B+ tree) to `ion_file` must be resolved to use standard C file IO.

Also refer to issue "#ifdef ION_ARDUINO in B+ tree", as removing `ion_file` will resolve that issue as well. #3

**Comment by Stickerpants** [comment]
This task is under re-consideration, as `ion_file` has proved more important than originally thought.
