### ISSUE TITLE
All unit tests to be migrated to PlanckUnit

### ISSUE THREAD

**Issue by iondbproject** [iondbproject/iondb#19]
Currently, all IonDB unit tests use the CuTest library. We now have an in-house unit testing library named PlanckUnit, which can be found [here](https://github.com/iondbproject/PlanckUnit).

The goal is to migrate all of our unit tests to use PlanckUnit. Realistically, this should just amount to changing method calls from the CuTest name to the Planck name.

Steps:

1. Pull the master IonDB branch and make sure you can build and run the existing unit tests and have them all pass.

2. Pull Planck Unit and make sure you can build and run the example for Planck Unit.

3. **branch** off IonDB/master to a planck branch. Integrate Planck Unit.

4. Once all tests pass once again, merge the planck branch back into master.

**Comment by Stickerpants** [comment]
Task done and merged to development.
