### ISSUE TITLE
#ifdef usage to be changed to be #if defined()

### ISSUE THREAD

**Issue by iondbproject** [iondbproject/iondb#20]
Currently, any time we do conditional compilation, it is done using the #ifdef directive. To allow for compound conditionals such as A && !B, switch all usage of #ifdef to be #if defined() instead.

**Comment by Stickerpants** [comment]
Task in progress by @danaack.

**Comment by danaack** [comment]
All #ifdef and #ifndef changes have been made. Changes are to be committed tomorrow.

**Comment by Stickerpants** [comment]
Changes merged into development. Ref 11d9dda233
