### ISSUE TITLE
Create C++ Wrapper for Arduino

### ISSUE THREAD

**Issue by iondbproject** [iondbproject/iondb#21]
Currently, working with IonDB "feels like" a C library. Write a C++ wrapper that simplifies the usage of IonDB to bring it more in line with how a typical Arduino library is used. The goal is to remove burden from the user and free them from tasks such as having to manually `malloc` memory for keys and values.

**Comment by Stickerpants** [comment]
Good progress is being made on this by @danaack, see ref 2179de5a1733114a8546a3e1282a7b0f41aa9c0e

**Comment by Stickerpants** [comment]
Task has been done and merged into development.
