### ISSUE TITLE
 #ifdef ION_ARDUINO clauses in B+ tree

### ISSUE THREAD

**Issue by iondbproject** [iondbproject/iondb#3]
[this](https://github.com/iondbproject/iondb/blob/fd9106be984f4287ab1f1c18df4c3749884dac24/src/dictionary/bpptree/bpptree.c#L691-L695) and other places have hacky clauses put in to handle compilation on device. Code should be refactored in such a way that the clauses are no longer needed.

This ties into the other issue "Delete ion_file". When ion_file is removed, this issue will be resolved as well. #14

**Comment by Stickerpants** [comment]
Note that the macro has been renamed to ARDUINO and ION_ARDUINO no longer exists. (This change is pending push from @wpenson)

**Comment by Stickerpants** [comment]
Issue moved to internal task tracker.
