### ISSUE TITLE
Add iondb to Arduino Library Manager

### ISSUE THREAD

**Issue by vvhof** [iondbproject/iondb#32]
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by danaack** [comment]
Hi @vvhof! We appreciate your suggestion and we are looking into registering IonDB with the library manager.

**Comment by vvhof** [comment]
Hi @danaack 
Appreciated :)

**Comment by Stickerpants** [comment]
Hi @vvhof, just wanted to let you know that we have submitted IonDB to the library manager with the culmination of the public release we just pushed today. You can find [our submission here](https://github.com/arduino/Arduino/issues/5117).

Thanks again for the suggestion!

**Comment by vvhof** [comment]
Thank @Stickerpants !
