### ISSUE TITLE
Generalized functional tests to be created

### ISSUE THREAD

**Issue by iondbproject** [iondbproject/iondb#7]
Currently, we have a set of tests called `generic_dictionary_test`. These set of tests operate on black box style dictionaries, and only assert at the dictionary level the correctness of the dictionary. However, these tests only define the individual tests themselves, but no suite of tests has been made yet.

A suite of tests should be written that utilize the `generic_dictionary_test` functionality, covering all use cases and edge cases. The goal is to be able to pass in the handler for different implementations, and it run the tests. This is useful in answering the question, "Does this implementation support all the functionality we need it to?"

Refer to B+ tree tests, as it does something very similar already. We just need to pull it out into a more generalized test loader.

**Comment by Stickerpants** [comment]
Following the creation of the behaviour tests, this task is complete.
